### ISSUE TITLE
No longer able to run rootless

### ISSUE THREAD

**Issue by SkewedZeppelin** [JonMagon/KDiskMark#101]
- Linux-distro (kernel version): Fedora 36/Linux 5.19.9 
- Desktop Environment (KDE/GNOME etc.): GNOME
- Qt Version: 5.15.5
- KDiskMark Version: 3.1.2
- FIO Version: fio-3.29

### Description:
Previously in 2.x you could run without granting privileges by simply disabling the flush option.
Now even with it unchecked, there is still a polkit prompt to elevate permissions.

> polkitd[782]: Operator of unix-session:2 successfully authenticated as unix-user:admin to gain TEMPORARY authorization for action dev.jonmagon.kdiskmark.helper.init for system-bus-name::1.174 [kdiskmark] (owned by unix-user:admin)

Is this a bug with starting the helper when it isn't neceesary?
or is there a new use that needs elevated perms?
 
### Steps To Reproduce:
- Uncheck "Flush Pagecache"
- Start a test
- See polkit prompt

**Comment by JonMagon** [comment]
This is expected behavior, 3.x.x performs testing entirely inside the helper, it avoids problems: inability to write to some places, repeated authorization requests. Note, however, that in the initial 3.0.0 authorization is not secure, this version should not be used, due to CVE-2022-40673, discovered during a review by the SUSE security team. Versions 3.1.0 and above aren't affected. 
You can also use AppImage and Snap, they do not technically support the helper, so it is not there, but it will cause the problems I listed above.

**Comment by Mart-Bogdan** [comment]
Hello, @JonMagon can you pleas describe what is this helper? I'm newbie developer new to Linux, so would be cool to hear details. 


P.S. As I understand #113 and #114 aren't possible due to same reason?

**Comment by xsetiadi** [comment]
i have other issue regardles to this, the window that supposedly to give password not appear. it only shows could not obtain administrator privileges.

I'm using orangepi5 remote the system via windows use xrdp

**Comment by SkewedZeppelin** [comment]
@OzzyHelix 
that is unrelated
you can workaround it by adding `user_allow_other` to `/etc/fuse.conf`
