### ISSUE TITLE
Comparable to CrystalDiskMark?..

### ISSUE THREAD

**Issue by tbone2k-git** [JonMagon/KDiskMark#134]
Is the data written / read to the disk comparable to what CrystalDiskMark does?
I ask because it's relevant when comparing filesystem performance and compression (btrfs, ntfs compression etc.).

If KDM and CDM would use same type of data, that would surely help to compare results. It does not make things totally equal, I know, but we should get much closer if both tools write the same data. If one tool would write randomized data and the other just plain zeros, performance would be very different if used with btfs/ntfs compression enabled - and not comparable at all.

Thank you! o)

ps: Why is there no reference/credit for CrystalDiskMark given in the description? Would it hurt? o)

**Comment by JonMagon** [comment]
You can choose the same settings in both tools. Results are not generally comparable, KDM uses FIO and CDM uses DISKSPD. It is also worth considering the overhead of different file systems. If you need to make accurate comparisons, use FIO's CLI instead of KDM/CDM.

The reference is just in the tags under the description.
