### ISSUE TITLE
No Debian issue, due to missing dependency

### ISSUE THREAD

**Issue by Jeremy7701** [JonMagon/KDiskMark#45]
Won't install in Debian from the .deb file because `libgcc-s1` doesn't exist in the repository.

**Comment by JonMagon** [comment]
`libgcc-s1` is included because of building on Ubuntu. There's no way to use Debian instead.
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#github-hosted-runners
You should build the package yourself or use `libgcc-s1` from the unstable repo, or wait while `libgcc-s1` will going to the stable one.

**Comment by JonMagon** [comment]
You can also try to install deb built for Ubuntu bionic: https://launchpad.net/~jonmagon/+archive/ubuntu/kdiskmark/+files/kdiskmark_2.1.1-2_amd64.deb

**Comment by JonMagon** [comment]
Try package built for MX Linux: http://ftp.linux.edu.lv/mxlinux/mx/repo/pool/main/k/kdiskmark/
