### ISSUE TITLE
Anyway to avoid asking for pass for dropping caches?

### ISSUE THREAD

**Issue by flying-x** [JonMagon/KDiskMark#81]
I searched around and couldn't find an answer. This is a really nice tool. I am wondering is there a way to run it unattended without typing password when it needs to drop caches? I suppose that I could run into as root, but that's kind of dangerous. Any ideas? Thanks a lot!

**Comment by flying-x** [comment]
What seems to be happening is that there is a new helper process gets created and end up asking for permission again?

![image](https://user-images.githubusercontent.com/22962929/167518953-37a4f637-629f-47fb-93a1-7905e4b7f873.png)

**Comment by flying-x** [comment]
BTW, I am on Manjaro

**Comment by flying-x** [comment]
Also, if I didn't notice the password dialog and had some delay entering it, kdiskmark will pop an error like "could not contact the helper" or something like that and abort the testing. :-(

**Comment by JonMagon** [comment]
Polkit is a great solution, but it has a time limit: https://cgit.freedesktop.org/polkit/tree/src/polkitbackend/polkitbackendinteractiveauthority.c#n3271
The only possible solution in my opinion is to create a daemon, but this seems excessive for this small app.
Starting a new process with root privileges also fails because it will be killed before testing is finished. There is essentially no way to communicate via dbus for an extended period of time, or I am not aware of it.

**Comment by flying-x** [comment]
Thank you so much for the answer! That makes a lot of sense now.

How about creating a small script with SUID that its only job is to drop caches, like drop_cache.sh, which is then installed with root user and a SUID flag?

**Comment by JonMagon** [comment]
It sounds good. I'll get to it when I have time.

**Comment by rshalaev** [comment]
I confirm - same issue on Ubuntu. During test KDiskMark shows a pop-up asking enter elevated permissions password, this happens at the beginning, and then several times during test. If it's not entered quickly - test will abort with DBUS error. This is troublesome because that means that I need to keep an eye at all times during the test.

**Comment by JonMagon** [comment]
Started working on this in the `daemonize` branch. Let's see what comes out of it.
